# Order?

# 1. Revisions: why revisions? how revisions work?
#               full reference of a Conan package
#               what affects the recipe revision?
#               what affects the package revision?

# 2. Package ID modes: 

# 3. Lockfiles: locking dependencies in a lockfile 

# Installing specific revisions in a graph

# 4. Build info: generating build information from lockfiles 
#                publishing build info to artifactory
#                merge build info generated by different build nodes

# Storing lockfiles in generic repos?
